name: My First Workflow

# on: push
on: 
  pull_request:

jobs:
  test: #job 1
    runs-on: ubuntu-latest

    steps:
      - name: checkout code #setup project /clon
        uses: actions/checkout@v4
        
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: check node version
        run: node -v
      - name: dounload dependncy
        run: npm i
      - name: run test
        run: npm run test    
      # - name: list file
        # run: ls
# name: My First Workflow

# on: push

# jobs:
#   deply-app: #job 1
#     runs-on: ubuntu-latest

#     steps:
#       - name: Print messages
#         run: |
#           echo "Hello, GitHub Actions!"
#           echo "Veer Vanshaj"
#   say-bye:  #job 2
#     runs-on: ubuntu-latest
#     needs: deply-app
#     steps:
#       - name: Print messages
#         run: echo "Goodbye from second job"
          
# name: My First Workflow

# on: push

# jobs:
#   say-hello:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Print messages
#         run: |
#           echo "Hello, GitHub Actions!"
#           echo "Veer Vanshaj"
#   say-bye:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Print messages
#         run: echo "Goodbye from second job"
          