name: My First Workflow

on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print messages
        run: |
          echo "Hello, GitHub Actions!"
          echo "Veer Vanshaj"
  say-bye:
    runs-on: ubuntu-latest

    steps:
      - name: Print messages
        run: echo "Goodbye from second job"
          